### Arrays

arrays是numpy中的数组类型，某一个arrays中的所有元素的数据类型必须是相同的

arrays的索引和常见的数组类似

arrays还有维数dimensions和形状shape的概念，dimensions是嵌套的层数，shape则是一个整数元组表示每一个dimension的size

In [1]:
import numpy as np # 导入numpy

#### **一些创建arrays的方式**
- 由数组创建
- `np.zeros`和`np.ones`创建指定形状全0或全1 arrays
- `np.full`创建指定形状的用某个数填充的arrays
- `np.eye`创建n维的单位矩阵
- `np.random.random`随机数矩阵

In [2]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [3]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [4]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [5]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [6]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.20589207 0.29662295]
 [0.27986914 0.1219364 ]]
